[package]
name = "yagetopts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
serde = { version = "1.0.156", features = ["derive"] }
serde_yaml = "0.9.19"
